### PR TITLE
fix #81 remove ashr from API and fix shr on Nim 0.20

### LINKED ISSUE #81: 0.20 compat - signed int SHR / right shift is broken
Signed integer right shift is broken on 0.20, can be reproduced by running the test suite with 0.20.

Unsigned integers are not affected

### PR DESCRIPTION
**Pull request by jangko**
this is a breaking changes, nimbus need update when this PR is merged

### CODE REVIEW

File: stint/private/int_bitwise_ops.nim [hunk 1]
```diff
@@ -56,42 +53,46 @@ func `shl`*(x: IntImpl, y: SomeInteger): IntImpl {.inline.}=
...
-  elif y < halfSize:
-    result.lo = (x.lo shr y) or convert[LoType](x.hi shl (halfSize - y))
-    result.hi = ashr(x.hi, y)
-  else:
-    result.lo = convert[LoType](ashr(x.hi, (y - halfSize)))
-    result.hi = ashr(x.hi, halfSize-1)
+template nimVersionIs(comparator: untyped, major, minor, patch: int): bool =
+  comparator(NimMajor * 100 + NimMinor * 10 + NimPatch, major * 100 + minor * 10 + patch)
+
+when nimVersionIs(`>=`, 0, 20, 0):
```
Comment (arnetheduck) [inline stint/private/int_bitwise_ops.nim]: when `(NimMajor,NimMinor,NimPatch) >= (0, 20, 0)` should work without the template using tuple comparison
